//OTHER STATE MANAGEMENT ACTIONS//
export const SET_START_ASSESSMENT_MODAL = 'SET_START_ASSESSMENT_MODAL'
export const SET_STAFF_CLIENT_LINK_MODAL = 'SET_STAFF_CLIENT_LINK_MODAL'
export const SET_STAFF_CLIENT_LINK_PANEL = 'SET_STAFF_CLIENT_LINK_PANEL'
export const SET_CONSULT_UPLOAD_MODAL = 'SET_CONSULT_UPLOAD_MODAL'
export const SET_UPDATE_CLIENT_CONFIRM_MODAL = 'SET_UPDATE_CLIENT_CONFIRM_MODAL'
export const SET_REGISTER_STAFF_MODAL = 'SET_REGISTER_STAFF_MODAL'
export const SET_REGISTER_STAFF_CONFIRM_MODAL = 'SET_REGISTER_STAFF_CONFIRM_MODAL'
export const SET_START_ASSESSMENT_CONFIRM_MODAL = 'SET_START_ASSESSMENT_CONFIRM_MODAL'
export const SET_EMAIL_REPORT_MODAL = 'SET_EMAIL_REPORT_MODAL'
export const SET_UPDATE_STAFF_MODAL = 'SET_UPDATE_STAFF_MODAL'
export const SET_UPDATE_STAFF_CONFIRM_MODAL = 'SET_UPDATE_STAFF_CONFIRM_MODAL'

export const SET_CURRENT_ASSESSMENT_ID = 'SET_CURRENT_ASSESSMENT_ID'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'
export const SET_UPLOADING_SUMMARY_REPORT = 'SET_UPLOADING_SUMMARY_REPORT'
export const SET_UPLOADING_ACTIGRAM = 'SET_UPLOADING_ACTIGRAM'
export const SET_PROCESSING_XLSX_CSV = 'SET_PROCESSING_XLSX_CSV'
export const SET_UPLOADING_CONSULT_NOTES = 'SET_UPLOADING_CONSULT_NOTES'

export const CACHE_QUESTIONNAIRE_CHANGES = 'CACHE_QUESTIONNAIRE_CHANGES' //setting the changes to the quesitonnaire in redux, while changing sections within the questionnaire phase
export const CACHE_CONSULT_NOTES = 'CACHE_CONSULT_NOTES'
export const SET_IS_SUMMARY_REPORT = 'SET_IS_SUMMARY_REPORT'

export const SET_CONFIRM_MODAL_QUESTIONNAIRE = 'SET_CONFIRM_MODAL_QUESTIONNAIRE'
export const SET_CONFIRM_MODAL_CONSULT = 'SET_CONFIRM_MODAL_CONSULT'
export const SET_CONFIRM_MODAL_ACTIGRAM = 'SET_CONFIRM_MODAL_ACTIGRAM'
export const SET_CONFIRM_MODAL_ANALYSIS = 'SET_CONFIRM_MODAL_ANALYSIS'
export const SET_CONFIRM_MODAL_ASSESSMENT = 'SET_CONFIRM_MODAL_ASSESSMENT'

export const SET_CONFIRM_MODAL_DELETE_STAFF = 'SET_CONFIRM_MODAL_DELETE_STAFF'
export const SET_CONFIRM_MODAL_DELETE_CLIENT = 'SET_CONFIRM_MODAL_DELETE_CLIENT'

export const SET_PHASE_COMPLETE = 'SET_PHASE_COMPLETE'
export const SET_STAFF_DELETE_LOADING_COMPLETE = 'SET_STAFF_DELETE_LOADING_COMPLETE'

export const SET_REMOVING_FILE_COMPLETE = 'SET_REMOVING_FILE_COMPLETE'
export const SET_UPDATING_CLIENT_COMPLETE = 'SET_UPDATING_CLIENT_COMPLETE'
export const SET_REGISTERING_STAFF_COMPLETE = 'SET_REGISTERING_STAFF_COMPLETE'
export const SET_UPDATING_STAFF_COMPLETE = 'SET_UPDATING_STAFF_COMPLETE'
export const SET_START_ASSESSMENT_COMPLETE = 'SET_START_ASSESSMENT_COMPLETE'

export const SET_ASSESSMENT_ERROR = "SET_ASSESSMENT_ERROR"

export const SET_USER_ERROR = "SET_USER_ERROR"
export const SET_CLIENT_ERROR = "SET_CLIENT_ERROR"

export const SAVE_USER_DETAILS = "SAVE_USER_DETAILS"


//ADMIN ACTIONS//
export const UPDATE_PRIVILEGES_START = 'UPDATE_PRIVILEGES_START'
export const UPDATE_PRIVILEGES_SUCCESS = 'UPDATE_PRIVILEGES_SUCCESS'
export const UPDATE_PRIVILEGES_FAIL = 'UPDATE_PRIVILEGES_FAIL'

export const FETCH_CLIENTS_START = 'FETCH_CLIENTS_START'
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS'
export const FETCH_CLIENTS_FAIL = 'FETCH_CLIENTS_FAIL'

export const FETCH_STAFF_START = 'FETCH_STAFF_START'
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS'
export const FETCH_STAFF_FAIL = 'FETCH_STAFF_FAIL'

export const REGISTER_STAFF_USER_START = 'REGISTER_STAFF_USER_START'
export const REGISTER_STAFF_USER_SUCCESS = 'REGISTER_STAFF_USER_SUCCESS'
export const REGISTER_STAFF_USER_FAIL = 'REGISTER_STAFF_USER_FAIL'

export const CREATE_STAFF_CLIENT_LINK_START = 'CREATE_STAFF_CLIENT_LINK_START'
export const CREATE_STAFF_CLIENT_LINK_SUCCESS = 'CREATE_STAFF_CLIENT_LINK_SUCCESS'
export const CREATE_STAFF_CLIENT_LINK_FAIL = 'CREATE_STAFF_CLIENT_LINK_FAIL'

export const DELETE_STAFF_CLIENT_LINK_START = 'DELETE_STAFF_CLIENT_LINK_START'
export const DELETE_STAFF_CLIENT_LINK_SUCCESS = 'DELETE_STAFF_CLIENT_LINK_SUCCESS'
export const DELETE_STAFF_CLIENT_LINK_FAIL = 'DELETE_STAFF_CLIENT_LINK_FAIL'

export const DELETE_STAFF_START = 'DELETE_STAFF_START'
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS'
export const DELETE_STAFF_FAIL = 'DELETE_STAFF_FAIL'

export const UPDATE_STAFF_START = 'UPDATE_STAFF_START'
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS'
export const UPDATE_STAFF_FAIL = 'UPDATE_STAFF_FAIL'

export const DELETE_CLIENT_START = 'DELETE_CLIENT_START'
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS'
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL'

export const UPDATE_CLIENT_START = 'UPDATE_CLIENT_START'
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS'
export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL'

export const UPDATE_CLIENTALL_START = 'UPDATE_CLIENTALL_START'
export const UPDATE_CLIENTALL_SUCCESS = 'UPDATE_CLIENTALL_SUCCESS'
export const UPDATE_CLIENTALL_FAIL = 'UPDATE_CLIENTALL_FAIL'

export const SEARCH_STAFF_START = 'SEARCH_STAFF_START'
export const SEARCH_STAFF_SUCCESS = 'SEARCH_STAFF_SUCCESS'
export const SEARCH_STAFF_FAIL = 'SEARCH_STAFF_FAIL'

export const DELETE_ASSESSMENT_START = 'DELETE_ASSESSMENT_START'
export const DELETE_ASSESSMENT_SUCCESS = 'DELETE_ASSESSMENT_SUCCESS'
export const DELETE_ASSESSMENT_FAIL = 'DELETE_ASSESSMENT_FAIL'

export const SEARCH_CLIENTS_START = 'SEARCH_CLIENTS_START'
export const SEARCH_CLIENTS_SUCCESS = 'SEARCH_CLIENTS_SUCCESS'
export const SEARCH_CLIENTS_FAIL = 'SEARCH_CLIENTS_FAIL'

//ACTIONS
export const CREATE_CLIENT_START = 'CREATE_CLIENT_START'
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS'
export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL'

export const FETCH_CLIENT_START = 'FETCH_CLIENT_START'
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS'
export const FETCH_CLIENT_FAIL = 'FETCH_CLIENT_FAIL'

export const FETCH_STAFF_CLIENTS_START = 'FETCH_STAFF_CLIENTS_START'
export const FETCH_STAFF_CLIENTS_SUCCESS = 'FETCH_STAFF_CLIENTS_SUCCESS'
export const FETCH_STAFF_CLIENTS_FAIL = 'FETCH_STAFF_CLIENTS_FAIL'

export const SEARCH_CLIENTS_LINK_MODAL_START = 'SEARCH_CLIENTS_LINK_MODAL_START'
export const SEARCH_CLIENTS_LINK_MODAL_SUCCESS = 'SEARCH_CLIENTS_LINK_MODAL_SUCCESS'
export const SEARCH_CLIENTS_LINK_MODAL_FAIL = 'SEARCH_CLIENTS_LINK_MODAL_FAIL'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAIL = 'TOKEN_REFRESH_FAIL';

export const CHANGE_STAFF_PASSWORD_START = 'CHANGE_STAFF_PASSWORD_START'
export const CHANGE_STAFF_PASSWORD_SUCCESS = 'CHANGE_STAFF_PASSWORD_SUCCESS'
export const CHANGE_STAFF_PASSWORD_FAIL = 'CHANGE_STAFF_PASSWORD_FAIL'

export const VERIFY_TOKEN_START = 'VERIFY_TOKEN_START';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAIL = 'VERIFY_TOKEN_FAIL'

export const START_ASSESSMENTS_START = 'START_ASSESSMENTS_START'
export const START_ASSESSMENTS_SUCCESS = 'START_ASSESSMENTS_SUCCESS'
export const START_ASSESSMENTS_FAIL = 'START_ASSESSMENTS_FAIL'

export const UPDATE_ASSESSMENT_START = 'UPDATE_ASSESSMENT_START'
export const UPDATE_ASSESSMENT_SUCCESS = 'UPDATE_ASSESSMENT_SUCCESS'
export const UPDATE_ASSESSMENT_FAIL = 'UPDATE_ASSESSMENT_FAIL'

export const UPLOAD_SUMMARY_REPORT_START = 'UPLOAD_SUMMARY_REPORT_START'
export const UPLOAD_SUMMARY_REPORT_SUCCESS = 'UPLOAD_SUMMARY_REPORT_SUCCESS'
export const UPLOAD_SUMMARY_REPORT_FAIL = 'UPLOAD_SUMMARY_REPORT_FAIL'

export const REMOVE_SUMMARY_REPORT_START = 'REMOVE_SUMMARY_REPORT_START'
export const REMOVE_SUMMARY_REPORT_SUCCESS = 'REMOVE_SUMMARY_REPORT_SUCCESS'
export const REMOVE_SUMMARY_REPORT_FAIL = 'REMOVE_SUMMARY_REPORT_FAIL'

export const REMOVE_ASSESSMENT_FILE_START = 'REMOVE_ASSESSMENT_FILE_START'
export const REMOVE_ASSESSMENT_FILE_SUCCESS = 'REMOVE_ASSESSMENT_FILE_SUCCESS'
export const REMOVE_ASSESSMENT_FILE_FAIL = 'REMOVE_ASSESSMENT_FILE_FAIL'

export const FETCH_ASSESSMENT_START = 'FETCH_ASSESSMENT_START'
export const FETCH_ASSESSMENT_SUCCESS = 'FETCH_ASSESSMENT_SUCCESS'
export const FETCH_ASSESSMENT_FAIL = 'FETCH_ASSESSMENT_FAIL'

export const ASSESSMENT_FILE_UPLOAD_START = "ASSESSMENT_FILE_UPLOAD_START"
export const ASSESSMENT_FILE_UPLOAD_SUCCESS = "ASSESSMENT_FILE_UPLOAD_SUCCESS"
export const ASSESSMENT_FILE_UPLOAD_FAIL = "ASSESSMENT_FILE_UPLOAD_FAIL"

export const GENERATE_REPORT_START = "GENERATE_REPORT_START"
export const GENERATE_REPORT_SUCCESS = "GENERATE_REPORT_SUCCESS"
export const GENERATE_REPORT_FAIL = "GENERATE_REPORT_FAIL"

export const EMAIL_REPORT_START = "EMAIL_REPORT_START"
export const EMAIL_REPORT_SUCCESS = "EMAIL_REPORT_SUCCESS"
export const EMAIL_REPORT_FAIL = "EMAIL_REPORT_FAIL"